### ISSUE TITLE
SB: Unable to Add new Campaign (IE)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/SANDBOX-CPLplus-#1]
1) Get to the http://sandbox.cplplus.com/campaigns
2) Under "Campaigns" there are several controls/buttons
3) Click on **ADD**
4) Observe - nothing happens
![sb-campain-add-issue1](https://cloud.githubusercontent.com/assets/15894297/11759419/00a8042e-a048-11e5-9432-5b0db83117da.png)

**Comment by brendan-finmc** [comment]
fixed

**Comment by andrewkhomski** [comment]
Verified and closed.
