### ISSUE TITLE
SB: Unable to Edit an existing Campaign (IE)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/SANDBOX-CPLplus-#2]
1) Navigate to this page:
http://sandbox.cplplus.com/campaigns
2) Select any campaign
3) Click on the **Edit** button
4) Observe nothing happens.

**Comment by brendan-finmc** [comment]
fixed as related to previous

**Comment by andrewkhomski** [comment]
Verified the fix. Closing this DF.
