### ISSUE TITLE
SB: The filter doesn't work for "Cake Id" column (IE)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/SANDBOX-CPLplus-#3]
1) Navigate to this page
http://sandbox.cplplus.com/offers
2) Enter any eligible value (ex: 333) under the **Cake Id** column
3) Observe it won't filter

![sb-offer-filter1](https://cloud.githubusercontent.com/assets/15894297/11759758/01f4d4d4-a051-11e5-8b87-4ee60a7ad2de.png)

**Comment by brendan-finmc** [comment]
fixed

**Comment by andrewkhomski** [comment]
Closing. Switching to new repo:

https://github.com/listjunction/theplusnetwork/issues
