### ISSUE TITLE
SB: The filter doesn't work for "Advertiser Name" column (IE)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/SANDBOX-CPLplus-#4]
1) Navigate to this page
http://sandbox.cplplus.com/offers
2) Enter any eligible value (ex: DTI) under the **Advertiser Name** column
3) Observe it won't filter

**Comment by brendan-finmc** [comment]
fixed

**Comment by andrewkhomski** [comment]
This issue is now fixed and verified. Closing DF.
