### ISSUE TITLE
SB: Add new Publisher page doesn't provide error log / description

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/SANDBOX-CPLplus-#6]
SB: Add new Publisher page doesn't provide error log / description.

1) Navigate to this page:
http://sandbox.cplplus.com/account/register
2) Enter random data and observe the error:
_An error has occurred_.
Note - no explanation on what the issue is

**Comment by brendan-finmc** [comment]
Unable to reproduce error

**Comment by andrewkhomski** [comment]
Brendan - see the attached screen shot

![sb-issue-6](https://cloud.githubusercontent.com/assets/15894297/11800232/9f8a6822-a2a8-11e5-8d96-39aa2a585aab.png)

**Comment by andrewkhomski** [comment]
DF is transferred to new repo:
https://github.com/listjunction/theplusnetwork/issues
