### ISSUE TITLE
SB: Reports page lists only 2 publishers (Conversion Report)

### ISSUE THREAD

**Issue by andrewkhomski** [andrewkhomski/SANDBOX-CPLplus-#8]
1) Navigate to this page
http://sandbox.cplplus.com/report/conversions
2) Observe that there are only 2 Publishers listed: "AddWins LLC" and "Financial Juice"

**Comment by brendan-finmc** [comment]
Working as designed, User is only allowed to see publishers linked to account. My account only has 2 publishers.

**Comment by brendan-finmc** [comment]
Will need to discuss with harry/bob to see if they want an admin account to have access to all publishers

**Comment by andrewkhomski** [comment]
I understand. Can you see how to link more publishers to be linked to this account?
Also is there a way we can create another account for my user (andrewkhomski@gmail.com)? Or only Harry can do so?

**Comment by andrewkhomski** [comment]
Closing this DF as it is moved to new repo.
